name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x   # تأكد من الإصدار الصح لمشروعك
    - name: Restore dependencies
      run: dotnet restore UrlShortener.sln
    - name: Build
      run: dotnet build UrlShortener.sln --no-restore
    - name: Test
      run: dotnet test UrlShortener.sln --no-build --verbosity normal
      
  notifyTelegram:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: send custom message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.Telegram_To }}
        token: ${{ secrets.Telegram_Token }}
        format: html
        message: |
          ${{ needs.build.result == 'success' && '✅ <b>Build Succeeded!</b>' || '❌ <b>Build Failed!</b>' }}
          📦 <b>Repo:</b> <code>${{ github.repository }}</code>
          🌿 <b>Branch:</b> <code>${{ github.ref_name }}</code>
          👤 <b>By:</b> ${{ github.actor }}
          🔗 <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Run</a>